### ISSUE TITLE
Steps to reproduce Github error

### ISSUE THREAD

**Issue by Markavian** [subsidel/octo-credits#5]
![reproducable-git-credits-error](https://cloud.githubusercontent.com/assets/1431385/8172056/b561e59a-13b4-11e5-86b3-58ad4f0af1b7.png)

I've got some error checking in my `<octo-credits>` component template for the case where Github throws back the error response. See the screenshot.

Reproducable steps:
* Make a commit to the repository
* Have octo-credits do its stuff
* Error response returned
* Have octo-credits do its stuff again
* Normal response returned

Using this template now:
```html
<template tagName="octo-credits" data-source-template="/api/octoCredits/{{data-user}}/{{data-repo}}" refresh-time="300">
  <p>Credits for <b>{{data-user}}</b>/<b>{{data-repo}}</b> : </p>
  <p>
  {{#unless data.error}}
    {{#unless data}}
      <b>{{dataSourceStatus}}</b>
    {{/unless}}
    {{#each data}}
      <a href="{{html_url}}" class="octo-credits-link">
        <button class="btn btn-primary octo-credits-button">
          <img src="{{avatar}}" alt="{{name}}" style="max-height: 30px;" />
          <span class="octo-credits-name">{{name}}</span>
          <span class="badge octo-credits-commits">{{commits}}</span>
          <span class="badge octo-credits-additions">{{additions}}</span>
          <span class="badge octo-credits-deletions">{{deletions}}</span>
        </button>
      </a>
    {{/each}}
  {{/unless}}

  {{#if data.error}}
  <b>Error: was unable to retrieve credits, you may need to refresh.</b>
  <pre>{{dataSourceData}}</pre>
  {{/if}}
  </p>
</template>
```

**Comment by subsidel** [comment]
If the github api passes through an error, it should be handled by whomever consumes the api, not octo-credits, closing as not valid.
